[package]
name = "teloc"
version = "0.1.0"
authors = ["p0lunin <dmytro.polunin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frunk = "0.3.1"
once_cell = "1.4.1"
teloc_macros = { path = "../teloc_macros" }

[dev-dependencies]
uuid = { version = "0.8.1", features = ["v4"] }