on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

name: Continuous integration

jobs:
  code-checks teloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Cargo fmt
        run: cd teloc && cargo +nightly fmt --all -- --check
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo clippy
        run: cd teloc && cargo clippy --all --all-targets --all-features -- -D warnings

  test teloc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        run: cd teloc && cargo build

      - name: Test
        uses: actions-rs/cargo@v1
        run: cd teloc && cargo test

  code-checks macros:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Cargo fmt
        run: cd teloc-macros && cargo +nightly fmt --all -- --check
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo clippy
        run: cd teloc && cargo clippy --all --all-targets --all-features -- -D warnings

    build macro:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          rust:
            - stable
            - beta
            - nightly

      steps:
        - uses: actions/checkout@v2

        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: ${{ matrix.rust }}
            override: true

        - name: Build
          uses: actions-rs/cargo@v1
          run: cd teloc-macros && cargo build

        - name: Test
          uses: actions-rs/cargo@v1
          run: cd teloc-macros && cargo test

